### ISSUE TITLE
authentication response and vp_token

### ISSUE THREAD

**Issue by siacomuzzi** [Sphereon-Opensource/SIOP-OID4VP#46]
Hi there,

Can you please confirm what version of the `OpenID Connect for Verifiable Presentations` draft are you implementing in the [release/v2.0.0](https://github.com/Sphereon-Opensource/did-auth-siop/tree/release/v2.0.0/) branch?

I thought you were following [v1.0-10 (22 April 2022)](https://openid.net/specs/openid-connect-4-verifiable-presentations-1_0-10.html), but there is a significant difference in the authentication response:

* [According to this draft](https://openid.net/specs/openid-connect-4-verifiable-presentations-1_0-10.html#name-self-issued-openid-provider), a successful authentication response should contains a `vp_token` parameter along with `id_token` and `state`. 
* But in the `release/v2.0.0` branch, just an id_token is submitted to the RP. https://github.com/Sphereon-Opensource/did-auth-siop/blob/dcc36321e2012f27ab049316480e9a1e8745b3e2/src/main/functions/HttpUtils.ts#L27-L35

Do you have plans to change this part or am I missing something?

Thank you!

**Comment by maikel-maas** [comment]
Hi @siacomuzzi,

We have an open pull request that is intended to be merged in the next few days which addresses that issue.

**Comment by nklomp** [comment]
This is fixed in v0.3.0
