### ISSUE TITLE
OID4VP verify problem

### ISSUE THREAD

**Issue by cindy-chin** [Sphereon-Opensource/SIOP-OID4VP#65]
Hi,
May I know there is a support for create authorization request on direct_post ode with the response_uri and verify it? because I cannot make it works

**Comment by cindy-chin** [comment]
verifyAuthorizationResponse() for this method, it asking for AuthorizationResponsePayload that need idToken, but I only have vpToken

**Comment by nklomp** [comment]
Hi @cindy-chin We are currently working on support for the latest version. That is the problem with ever moving specs ;)

I expect us to have something after the weekend

**Comment by nklomp** [comment]
> verifyAuthorizationResponse() for this method, it asking for AuthorizationResponsePayload that need idToken, but I only have vpToken

Could you elaborate a bit more on this one? The `AuthorizationResponsePayload` itself is listing both the id_token and vp_token as optional as it should:

![image](https://github.com/Sphereon-Opensource/SIOP-OID4VP/assets/13615304/07edb4d1-a0e6-4559-ade1-2f47cd91c7ac)

**Comment by cindy-chin** [comment]
Yup, thankiew, previously the function is checking if id_token is null, then it will throw some error, but i think your latest push have solve this issue.
