### ISSUE TITLE
Verified success event raised when verification fails

### ISSUE THREAD

**Issue by Haza85** [Sphereon-Opensource/SIOP-OID4VP#79]
If presentation verification fails (verified=false) in presentationVerificationCallback then application raise event AuthorizationEvents.ON_AUTH_RESPONSE_VERIFIED_SUCCESS

**Comment by nklomp** [comment]
Hi, did you test that with the latest release of a few hours ago, as it should be fixed https://github.com/Sphereon-Opensource/SIOP-OID4VP/releases/tag/v0.6.4

**Comment by Haza85** [comment]
Hi. Yes, issue fixed after updating to the 0.6.4 version. Thanks!

**Comment by nklomp** [comment]
Cool. Thx for reporting back
